//lib/extensions/localization_get.dart
import 'package:flutter_basics/l10n/app_localizations.dart';

extension LocalizationHelper on AppLocalizations {
  /// Access any string using its key from ARB file.
  String get(String key) {
    final map = {
      'question1_text': question1_text,
      'question1_option1': question1_option1,
      'question1_option2': question1_option2,
      'question1_option3': question1_option3,
      'question1_option4': question1_option4,
      'question1_hint1': question1_hint1,
      'question1_hint2': question1_hint2,
      'question1_solution': question1_solution,
      'question1_difficulty': question1_difficulty,
      'question2_text': question2_text,
      'question2_option1': question2_option1,
      'question2_option2': question2_option2,
      'question2_option3': question2_option3,
      'question2_option4': question2_option4,
      'question2_hint1': question2_hint1,
      'question2_hint2': question2_hint2,
      'question2_solution': question2_solution,
      'question2_difficulty': question2_difficulty,
      'question3_text': question3_text,
      'question3_option1': question3_option1,
      'question3_option2': question3_option2,
      'question3_option3': question3_option3,
      'question3_option4': question3_option4,
      'question3_hint1': question3_hint1,
      'question3_hint2': question3_hint2,
      'question3_solution': question3_solution,
      'question3_difficulty': question3_difficulty,
      'question4_text': question4_text,
      'question4_option1': question4_option1,
      'question4_option2': question4_option2,
      'question4_option3': question4_option3,
      'question4_option4': question4_option4,
      'question4_hint1': question4_hint1,
      'question4_hint2': question4_hint2,
      'question4_solution': question4_solution,
      'question4_difficulty': question4_difficulty,
      'question5_text': question5_text,
      'question5_option1': question5_option1,
      'question5_option2': question5_option2,
      'question5_option3': question5_option3,
      'question5_option4': question5_option4,
      'question5_hint1': question5_hint1,
      'question5_hint2': question5_hint2,
      'question5_solution': question5_solution,
      'question5_difficulty': question5_difficulty,
      'question6_text': question6_text,
      'question6_option1': question6_option1,
      'question6_option2': question6_option2,
      'question6_option3': question6_option3,
      'question6_option4': question6_option4,
      'question6_hint1': question6_hint1,
      'question6_hint2': question6_hint2,
      'question6_solution': question6_solution,
      'question6_difficulty': question6_difficulty,
      'question7_text': question7_text,
      'question7_option1': question7_option1,
      'question7_option2': question7_option2,
      'question7_option3': question7_option3,
      'question7_option4': question7_option4,
      'question7_hint1': question7_hint1,
      'question7_hint2': question7_hint2,
      'question7_solution': question7_solution,
      'question7_difficulty': question7_difficulty,
      'question8_text': question8_text,
      'question8_option1': question8_option1,
      'question8_option2': question8_option2,
      'question8_option3': question8_option3,
      'question8_option4': question8_option4,
      'question8_hint1': question8_hint1,
      'question8_hint2': question8_hint2,
      'question8_solution': question8_solution,
      'question8_difficulty': question8_difficulty,
      'question9_text': question9_text,
      'question9_option1': question9_option1,
      'question9_option2': question9_option2,
      'question9_option3': question9_option3,
      'question9_option4': question9_option4,
      'question9_hint1': question9_hint1,
      'question9_hint2': question9_hint2,
      'question9_solution': question9_solution,
      'question9_difficulty': question9_difficulty,
      'question10_text': question10_text,
      'question10_option1': question10_option1,
      'question10_option2': question10_option2,
      'question10_option3': question10_option3,
      'question10_option4': question10_option4,
      'question10_hint1': question10_hint1,
      'question10_hint2': question10_hint2,
      'question10_solution': question10_solution,
      'question10_difficulty': question10_difficulty,
      'question11_text': question11_text,
      'question11_option1': question11_option1,
      'question11_option2': question11_option2,
      'question11_option3': question11_option3,
      'question11_option4': question11_option4,
      'question11_hint1': question11_hint1,
      'question11_hint2': question11_hint2,
      'question11_solution': question11_solution,
      'question11_difficulty': question11_difficulty,
    };

    if (map.containsKey(key)) {
      return map[key]!;
    } else {
      return '**$key**'; // Useful for debugging missing keys
    }
  }
}
